# Generated by Django 5.1 on 2024-08-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='easy_plants.plant'),
        ),
        migrations.CreateModel(
            name='PlantEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=255)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='easy_plants.plant')),
            ],
        ),
    ]
