# Generated by Django 5.1 on 2024-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_plants', '0002_alter_plantimage_plant_plantentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantentry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='plantentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
