# Generated by Django 5.1 on 2024-08-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_plants', '0004_plant_archived_plant_flowering_start_plant_harvested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='flowering_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='harvested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
