# Generated by Django 5.1 on 2024-11-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_plants', '0005_alter_plant_flowering_start_alter_plant_harvested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='day_one',
            field=models.DateField(blank=True, null=True),
        ),
    ]
