# Generated by Django 5.1 on 2024-11-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_plants', '0006_plant_day_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='drying_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
