# Generated by Django 5.1 on 2024-11-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_plants', '0007_plant_drying_end_alter_plantentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='yield_dry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='yield_wet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
